# -*- coding: utf-8 -*-
"""modelling_subimission

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XmtWEJ65-YjVjNpfD3NXSY3_Y7AvNPB
"""



import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# MLflow
import mlflow
import mlflow.sklearn


# =========================================================
# LOAD DATASET
# =========================================================
def load_data():
    print("\n[INFO] Loading dataset...")

    path = "IEA-EV-dataEV salesCarsHistorical_cleaned.csv"

    try:
        df = pd.read_csv(path)
    except Exception as e:
        print("[ERROR] Tidak dapat membaca file CSV!")
        print(e)
        raise SystemExit

    print("[INFO] Dataset shape:", df.shape)

    # Fitur & target
    X = df.drop(columns=["value"])
    y = df["value"]

    # Split data
    return train_test_split(X, y, test_size=0.2, random_state=42)


# =========================================================
# TRAINING MODEL
# =========================================================
def train_model(X_train, X_test, y_train, y_test, model_name):

    print("\n" + "="*60)
    print(f"[INFO] Training model: {model_name}")
    print("="*60)

    # Mengaktifkan autolog
    mlflow.sklearn.autolog()

    # Pilihan model
    if model_name == "DecisionTree":
        model = DecisionTreeRegressor(random_state=42)

    elif model_name == "RandomForest":
        model = RandomForestRegressor(
            n_estimators=150,
            max_depth=10,
            random_state=42
        )

        # Log parameter model
        mlflow.log_param("model_type", "RandomForest")
        mlflow.log_param("n_estimators", 150)
        mlflow.log_param("max_depth", 10)
        mlflow.log_param("random_state", 42)

    # Train
    model.fit(X_train, y_train)

    # Predict
    pred = model.predict(X_test)

    # Metrics
    mse = mean_squared_error(y_test, pred)
    r2 = r2_score(y_test, pred)

    print(f"MSE Score: {mse}")
    print(f"R² Score:  {r2}")

    # Tidak perlu mlflow.log_metric manual; autolog sudah menyimpan metrik
    print("[INFO] Model selesai dilatih dan disimpan ke MLflow.")


# =========================================================
# MAIN PROGRAM
# =========================================================
def main():

    print("\n" + "="*60)
    print("EV SALES REGRESSION - KINANTI")
    print("="*60)

    # Set experiment MLflow
    mlflow.set_experiment("EV_Sales_Regression_Kinanti")

    # Load data
    X_train, X_test, y_train, y_test = load_data()

    # Daftar model
    models = ["DecisionTree", "RandomForest"]

    # Train loop
    for m in models:
        train_model(X_train, X_test, y_train, y_test, m)

    print("\n[INFO] Training selesai!")
    print("\n[INFO] Untuk membuka MLflow UI:")
    print("1. Jalankan:   mlflow ui")
    print("2. Buka link:  http://localhost:5000")


# =========================================================
# EXECUTE
# =========================================================
if __name__ == "__main__":
    main() 
